### ISSUE TITLE
Dataset link has no content

### ISSUE THREAD

**Issue by themousepotato** [Rose-STL-Lab/Turbulent-Flow-Net#4]
Google drive of the dataset is an empty folder https://drive.google.com/drive/folders/1VOtLjfAkCWJePiacoDxC-nrgCREKvrpE?usp=sharing. Could you please share the dataset?

**Comment by akrzgc** [comment]
+1 for the issue, is there any way for reaching the dataset?

**Comment by Rui1521** [comment]
We have uploaded the data to the folder again. Sorry about that.

**Comment by wzkkk33** [comment]
Hello, the dataset has expired. Could you please share it again？
