### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/rwang2/TF-net/Data/data_64/sample_4889.pt'

### ISSUE THREAD

**Issue by iperezx** [Rose-STL-Lab/Turbulent-Flow-Net#5]
Do I need it? What can I replace this with?

**Comment by iperezx** [comment]
NVM I need to generate it with the dataset that is provided and run `data_gen.py`.

**Comment by wzkkk33** [comment]
Hello, do you still have this dataset? If possible, could you share it with me?
