### ISSUE TITLE
What are the compute, RAM, and Disk resource requirements to run?

### ISSUE THREAD

**Issue by iperezx** [Rose-STL-Lab/Turbulent-Flow-Net#6]
Unable to run as is. 

Made changes in this fork to run a small case: https://github.com/iperezx/Turbulent-Flow-Net

**Comment by iperezx** [comment]
I cant produce the data from data_gen.py as is because I run out of disk space with 5TB. I changed data_gen.py (https://github.com/iperezx/Turbulent-Flow-Net/blob/master/data_gen.py) to pass in input params to change how many files to create and that works with `-s 5`. Also one GPU doesn’t work if I increase the number of files from data_gen.py.

**Comment by Rui1521** [comment]
Hi, sorry for replying late. I didn't see your comment. There was an issue in data_gen.py and we just fixed it. Can you try again? Thanks!
